#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=testEXAMPLE
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:59:00
#SBATCH --output=out/testEXAMPLE-%A.out

#exit if an error occurs


module purge
module load 2023
module load Miniconda3/23.5.2-0
module load CUDA/12.1.1
module load cuDNN/8.9.2.26-CUDA-12.1.1

source activate transformers4rec_v2_akis

python tr4rec/pre_process.py --split small --data_category test --history_size 20 --dataset_type enriched
